on: push

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: debian:bullseye-slim
          artifacts-dir: debian/artifacts/bullseye
          buildpackage-opts: --build=binary --no-sign

      - uses: actions/upload-artifact@v3
        with:
          name: deb-test-bullseye
          path: ${{ github.workspace }}/debian/artifacts/bullseye

      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: debian:buster-slim
          artifacts-dir: debian/artifacts/buster
          buildpackage-opts: --build=binary --no-sign

      - uses: actions/upload-artifact@v3
        with:
          name: deb-test-buster
          path: ${{ github.workspace }}/debian/artifacts/buster
